# Learning Parameters
LEARNING_RATE : 0.0001
LEARNING_DECAY_STEP : 1000000
BATCH_SIZE : 128
TRAINING_ITERS : 2000000
DISPLAY_STEP : 10

# Network Data Parameters
NET : "berlinnet" # name of the Python file with the network specification
INPUT_SHAPE : [39, 600, 1] # Input Image shape
OUTPUT_SHAPE : [2] # Total classes as vector

# Datasets
TRAINING_DATA : "/home/vegeboy/workspace/uni/iLID-Data/output/train_shuffled.csv"
TEST_DATA : "/home/vegeboy/workspace/uni/iLID-Data/output/test_shuffled.csv"

# Logging
LOG_PATH : "logs"
SNAPSHOT_PATH : "snapshots"
ENABLE_EMAIL_NOTIFICATION : True
